### ISSUE TITLE
Error generating spatial label image

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-pipeline#98]
```
ERROR ~ Error executing process > 'Full_pipeline:Process_images:Generate_image ([test, visium], label, spaceranger210_count_47757_HCA_sCTCL13876505-GRCh38-2020-A)'

Caused by:
  Process `Full_pipeline:Process_images:Generate_image ([test, visium], label, spaceranger210_count_47757_HCA_sCTCL13876505-GRCh38-2020-A)` terminated with an error exit status (1)

Command executed:

  generate_image.py         --stem test-visium         --img_type label         --file_type visium         --file_path spaceranger210_count_47757_HCA_sCTCL13876505-GRCh38-2020-A         --ref_img V43J12-3342024-07-12-A1_microscope_STAN-1767D_P725-2023-07-11_12.55.05.ndpi_MAG1.49x_ROT0_BOX2234.2019_24732.2019_24732.18396_2234.18396.tif --args {}

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/home/ndh122/Projects/HaniffaLab/webatlas-pipeline/bin/generate_image.py", line 57, in <module>
      fire.Fire(create_img)
    File "/home/ndh122/anaconda3/envs/webatlas-0.3.2/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
      component_trace = _Fire(component, args, parsed_flag_args, context, name)
    File "/home/ndh122/anaconda3/envs/webatlas-0.3.2/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
      component, remaining_args = _CallAndUpdateTrace(
    File "/home/ndh122/anaconda3/envs/webatlas-0.3.2/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
      component = fn(*varargs, **kwargs)
    File "/home/ndh122/Projects/HaniffaLab/webatlas-pipeline/bin/generate_image.py", line 46, in create_img
      visium_label(stem, file_path, **args)
    File "/home/ndh122/Projects/HaniffaLab/webatlas-pipeline/bin/process_spaceranger.py", line 210, in visium_label
      label_img[disk((int(x), int(y)), spot_diameter_fullres / 2)] = int(5)
  IndexError: index 2079 is out of bounds for axis 1 with size 2079

Work dir:
  /home/ndh122/Projects/HaniffaLab/webatlas-pipeline/work/0e/fb751192a5033700c05674df27ce63

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details
```

**Comment by BioinfoTongLI** [comment]
is this the `visium-spot-outside-the-view` edge case?
If so, our conclusion was to discard those visium spots. As they are not carrying useful information.
I assume this is not yet done?
